package org.piramalswasthya.cho.model

import com.squareup.moshi.JsonClass

@JsonClass(generateAdapter = true)
data class BenDetailsDownsync(
    val benAnthropometryDetail: BenAnthropometryDetail?,
    val GOPDNurseVisitDetail: GOPDNurseVisitDetail?,
    val benPhysicalVitalDetail: BenPhysicalVitalDetail?,
    val BenChiefComplaints: List<BenChiefComplaints>?,
)

@JsonClass(generateAdapter = true)
data class BenAnthropometryDetail(
    val ID: Long?,
    val beneficiaryRegID: Long?,
    val benVisitID: Long?,
    val providerServiceMapID: Int?,
    val visitCode: Long?,
    val weight_Kg: Double?,
    val height_cm: Double?,
    val bMI: Double?,
    val headCircumference_cm: Double?,
    val midUpperArmCircumference_MUAC_cm: Double?,
    val hipCircumference_cm: Double?,
    val waistCircumference_cm: Double?,
    val waistHipRatio: Double?,
    val deleted: Boolean?,
    val processed: String?,
)

@JsonClass(generateAdapter = true)
data class GOPDNurseVisitDetail(
    val benVisitID: Long?,
    val beneficiaryRegID: Long?,
    val visitCode: Long?,
    val providerServiceMapID: Int?,
    val visitDateTime: String?,
    val visitNo: Int?,
    val visitReasonID: Int?,
    val visitReason: String?,
    val visitCategoryID: Int?,
    val visitCategory: String?,
    val pregnancyStatus: String?,
    val rCHID: String?,
    val healthFacilityType: String?,
    val healthFacilityLocation: String?,
    val reportFilePath: String?,
    val deleted: Boolean?,
    val processed: String?,
    val visitFlowStatusFlag: String?,
    val fileIDs: List<Int>?,
    val fpSideeffects: String?,
    val otherSideEffects: String?,
    val fpMethodFollowup: String?,
    val otherFollowUpForFpMethod: String?,
    val subVisitCategory: String?,
    val followUpForFpMethod: String?,
    val sideEffects: String?,
)

@JsonClass(generateAdapter = true)
data class BenPhysicalVitalDetail(
    val ID: Long?,
    val beneficiaryRegID: Long?,
    val benVisitID: Long?,
    val providerServiceMapID: Int?,
    val visitCode: Long?,
    val temperature: Double?,
    val pulseRate: Int?,
    val respiratoryRate: Int?,
    val systolicBP_1stReading: Int?,
    val diastolicBP_1stReading: Int?,
    val systolicBP_2ndReading: Int?,
    val diastolicBP_2ndReading: Int?,
    val systolicBP_3rdReading: Int?,
    val diastolicBP_3rdReading: Int?,
    val bloodPressureStatusID: Int?,
    val bloodPressureStatus: String?,
    val bloodGlucose_Fasting: Int?,
    val bloodGlucose_Random: Int?,
    val bloodGlucose_2hr_PP: Int?,
    val bloodGlucose_NotSpecified: Int?,
    val diabeticStatusID: Int?,
    val diabeticStatus: String?,
    val averageSystolicBP: Int?,
    val averageDiastolicBP: Int?,
    val capillaryRefillTime: String?,
    val rbsTestResult: String?,
    val rbsTestRemarks: String?,
    val sPO2: String?,
    val hemoglobin: Double?,
    val deleted: Boolean?,
    val processed: String?,
)

@JsonClass(generateAdapter = true)
data class BenChiefComplaints(
    val benChiefComplaintID: Long?,
    val beneficiaryRegID: Long?,
    val benVisitID: Long?,
    val providerServiceMapID: Int?,
    val visitCode: Long?,
    val chiefComplaintID: Int?,
    val chiefComplaint: String?,
    val conceptID: String?,
    val duration: Int?,
    val unitOfDuration: String?,
    val description: String?,
    val deleted: Boolean?,
    val processed: String?
)

//{
//
//    "data": {
//
//    "benAnthropometryDetail": {
//
//        "ID": 4612,
//        "beneficiaryRegID": 33459,
//        "benVisitID": 5430,
//        "providerServiceMapID": 265,
//        "visitCode": 30016800005430,
//        "weight_Kg": null,
//        "height_cm": null,
//        "bMI": null,
//        "headCircumference_cm": null,
//        "midUpperArmCircumference_MUAC_cm": null,
//        "hipCircumference_cm": null,
//        "waistCircumference_cm": null,
//        "waistHipRatio": null,
//        "deleted": false,
//        "processed": "N",
//        "createdBy": "Sanjay",
//        "createdDate": "Sep 14, 2023 8:44:51 PM",
//        "modifiedBy": null,
//        "lastModDate": "Sep 14, 2023 8:44:51 PM",
//        "vanSerialNo": null,
//        "vehicalNo": null,
//        "vanID": 168,
//        "parkingPlaceID": 83,
//        "syncedBy": null,
//        "syncedDate": null,
//        "reservedForChange": null
//    },
//
//    "GOPDNurseVisitDetail": {
//        "benVisitID": 5430,
//        "beneficiaryRegID": 33459,
//        "visitCode": 30016800005430,
//        "providerServiceMapID": 265,
//        "visitDateTime": null,
//        "visitNo": 1,
//        "visitReasonID": null,
//        "visitReason": "New Chief Complaint",
//        "visitCategoryID": null,
//        "visitCategory": "General OPD",
//        "pregnancyStatus": "No",
//        "rCHID": null,
//        "healthFacilityType": null,
//        "healthFacilityLocation": null,
//        "reportFilePath": "",
//        "deleted": false,
//        "processed": "N",
//        "createdBy": "Sanjay",
//        "createdDate": "Sep 14, 2023 8:44:51 PM",
//        "modifiedBy": null,
//        "lastModDate": "Sep 14, 2023 8:44:51 PM",
//        "visitFlowStatusFlag": "N",
//        "vanSerialNo": null,
//        "vehicalNo": null,
//        "vanID": 168,
//        "parkingPlaceID": 83,
//        "syncedBy": null,
//        "syncedDate": null,
//        "reservedForChange": null,
//        "fileIDs": [
//            null
//        ],
//        "fpSideeffects": null,
//        "otherSideEffects": null,
//        "fpMethodFollowup": null,
//        "otherFollowUpForFpMethod": null,
//        "subVisitCategory": "Management of Communicable Diseases including National Health Programs",
//        "followUpForFpMethod": null,
//        "sideEffects": null
//    },
//
//    "benPhysicalVitalDetail": {
//        "ID": 4611,
//        "beneficiaryRegID": 33459,
//        "benVisitID": 5430,
//        "providerServiceMapID": 265,
//        "visitCode": 30016800005430,
//        "temperature": null,
//        "pulseRate": null,
//        "respiratoryRate": null,
//        "systolicBP_1stReading": null,
//        "diastolicBP_1stReading": null,
//        "systolicBP_2ndReading": null,
//        "diastolicBP_2ndReading": null,
//        "systolicBP_3rdReading": null,
//        "diastolicBP_3rdReading": null,
//        "bloodPressureStatusID": null,
//        "bloodPressureStatus": null,
//        "bloodGlucose_Fasting": null,
//        "bloodGlucose_Random": null,
//        "bloodGlucose_2hr_PP": null,
//        "bloodGlucose_NotSpecified": null,
//        "diabeticStatusID": null,
//        "diabeticStatus": null,
//        "averageSystolicBP": null,
//        "averageDiastolicBP": null,
//        "capillaryRefillTime": null,
//        "rbsTestResult": null,
//        "rbsTestRemarks": null,
//        "sPO2": null,
//        "hemoglobin": null,
//        "deleted": false,
//        "processed": "N",
//        "createdBy": "Sanjay",
//        "createdDate": "Sep 14, 2023 8:44:51 PM",
//        "modifiedBy": null,
//        "lastModDate": "Sep 14, 2023 8:44:51 PM",
//        "vanSerialNo": null,
//        "vehicalNo": null,
//        "vanID": 168,
//        "parkingPlaceID": 83,
//        "syncedBy": null,
//        "syncedDate": null,
//        "reservedForChange": null
//    },
//
//    "BenChiefComplaints": [
//        {
//            "benChiefComplaintID": 2986,
//            "beneficiaryRegID": 33459,
//            "benVisitID": 5430,
//            "providerServiceMapID": 265,
//            "visitCode": 30016800005430,
//            "chiefComplaintID": 54,
//            "chiefComplaint": "Body Pains",
//            "conceptID": null,
//            "duration": 2,
//            "unitOfDuration": "Hours",
//            "description": null,
//            "deleted": null,
//            "processed": null,
//            "createdBy": null,
//            "createdDate": null,
//            "modifiedBy": null,
//            "lastModDate": null,
//            "vanSerialNo": null,
//            "vehicalNo": null,
//            "vanID": null,
//            "parkingPlaceID": null,
//            "syncedBy": null,
//            "syncedDate": null,
//            "reservedForChange": null
//        },
//        {
//            "benChiefComplaintID": 2987,
//            "beneficiaryRegID": 33459,
//            "benVisitID": 5430,
//            "providerServiceMapID": 265,
//            "visitCode": 30016800005430,
//            "chiefComplaintID": 428,
//            "chiefComplaint": "Vomiting",
//            "conceptID": "15387003",
//            "duration": 1,
//            "unitOfDuration": "Days",
//            "description": null,
//            "deleted": null,
//            "processed": null,
//            "createdBy": null,
//            "createdDate": null,
//            "modifiedBy": null,
//            "lastModDate": null,
//            "vanSerialNo": null,
//            "vehicalNo": null,
//            "vanID": null,
//            "parkingPlaceID": null,
//            "syncedBy": null,
//            "syncedDate": null,
//            "reservedForChange": null
//        }
//    ]
//},
//    "statusCode": 200,
//    "errorMessage": "Success",
//    "status": "Success"
//}
