
default_platform(:android)
platform :android do

  desc "Build and Distribute Debug APK to Firebase"
    lane :build_and_distribute_debug do |options|

     # Validate required environment variables
     required_env_vars = ['FIREBASE_APP_ID']
     required_env_vars.each do |var|
         UI.user_error!("Missing required environment variable: #{var}") if ENV[var].nil?
     end

     latest_release = firebase_app_distribution_get_latest_release(
        app: ENV['FIREBASE_APP_ID'],
        service_credentials_file: "firebase_credentials.json"
        ) rescue begin
               UI.important("Failed to fetch latest release, defaulting to version 1")
               OpenStruct.new(buildVersion: "0")
     )
     new_version_code = latest_release[:buildVersion].to_i + 1
     current_version_name = android_get_version_name
     new_version_name = "#{new_version_code}.0.0"

      File.open("../version/version.properties", "w") do |file|
          file.write("VERSION=#{new_version_name}")
      end

      # Build the debug variant
      gradle(
        task: "clean assemble#{options[:variant]}Debug"
      )

      # Distribute to Firebase App Distribution for Stag and UAT
      firebase_app_distribution(
        app: ENV['FIREBASE_APP_ID'],
        service_credentials_file: "firebase_credentials.json",
        release_notes_file: "FirebaseAppDistributionConfig/release_notes.txt",
        groups_file: "FirebaseAppDistributionConfig/groups.txt",
        debug: true
      )
    end





end